# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
labels:
  org.opencontainers.image.title: "SBFspot"
  org.opencontainers.image.description: "SBFspot"
  org.opencontainers.image.source: "https://github.com/J3173/home-assistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
