# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SBFspot
version: "0.0.3"
slug: sbfspot
description: Tool to read power production of SMA® solar inverters
url: "https://github.com/J3173/home-assistant-addons/tree/main/sbfspot"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
services:
  - mqtt:want
options:
  IP_Address: "0.0.0.0"
  Password: "0000"
  Interval: 60
schema:
  IP_Address: str
  Password: password
  Interval: int
image: "ghcr.io/j3173/{arch}-addon-sbfspot"
